% !Rnw root = duplicatessweave.Rnw

We can simulate having actually generated single end data by removing the connections between the two reads in a fragment. Although the true PCR duplicate rate is unchanged, the apparent duplicate rate is substantially higher as any two reads starting in the same location will appear to be duplicates (naturally a less-stringent criterion than having to start in the same location \textbf{and} have the same fragment length). 



<<SE Het SNP processing1,eval=FALSE>>=
HetSNPTableSE<-processBAMSE(bamfilelist=bamfilelist,path=path,snplist=snplist)
write.table(HetSNPTableSE,file="HetSNPTableSingleEnd.tsv",sep="\t")
@

<<SEHet SNP processing2,eval=TRUE>>=
HetSNPTableSE<-read.delim(file.path(EDpath,"HetSNPTableSingleEnd.tsv"),as.is=T,header=T)
SEests<-processduptable(HetSNPTableSE,PL,CL,reso=1001)
head(SEests)
@



A mean of 85\% of the duplicates seen when treating the data as single end are attributable to fragmentation duplicates, and the correction places the duplicate estimates in remarkable agreement with the estimates derived treating the data as 'paired-end'. 

<<AddFigC11-1, fig=TRUE, include=FALSE, width=8, height=6,eval=TRUE>>=
par(mfrow=c(1,2))
plot(FDres[,1],SEests[,1],pch=16,xlab="Basic estimate from PE data (%age)",ylab="Basic estimate from SE data (%age)",xlim=c(0,40),ylim=c(0,40))
abline(0,1)
plot(FDres[,3],SEests[,3],pch=16,xlab="Corrected estimate from PE data (%age)",ylab="Corrected estimate from SE data (%age)",xlim=c(0,12),ylim=c(0,12))
abline(0,1)
@
\incfig[ht!]{duplicatessweave-AddFigC11-1}{\textwidth}{Duplicate rates from paired- and single-end data}

<<PaperFigure1, fig=TRUE, include=FALSE, width=8, height=5,eval=TRUE>>=
par(mfrow=c(1,2))

plot(100*BasicEst/FDres[,3],FDres[,1]/FDres[,3],xlim=c(0.9,2.6),ylim=c(0.9,1.3),pch=16,xlab="Picard Estimate/Corrected Estimate",ylab="Observation from SNPs/Corrected Estimate",main="PCR duplicate rate")
abline(v=1,lwd=2)
abline(h=1,lwd=2)

plot(FDres[,3],SEests[,3],pch=16,xlab="Corrected estimate from PE data (%age)",ylab="Corrected estimate from SE data (%age)",xlim=c(0,12),ylim=c(0,12))
abline(0,1)
@


